apiVersion: k8s.crossplane.jonashackt.io/v1
kind: KubernetesCluster
metadata:
  namespace: default
  name: deploy-target-eks
spec:
  id: deploy-target-eks
  parameters:
    region: eu-central-1
    nodes:
      count: 3
  # Here we can define the name of the Secret Crossplane will populate the EKSClusters kubeconfig to
  # see https://docs.crossplane.io/latest/guides/connection-details-composition/
  writeConnectionSecretToRef:
    name: eks-cluster-kubeconfig
